import Foundation

// MARK: - Post-Call Report

/// Value object summarizing a completed coaching session.
/// Generated by ConversationCoach, persisted by CoachingPersistence, consumed by Views and export.
struct PostCallReport {
    let totalDuration: TimeInterval
    let movementTimeline: [(movement: ConversationMovement, start: TimeInterval, end: TimeInterval)]
    let memoryReport: ConversationMemory.CallReport
    let movementCount: Int
    let averageFluidityScore: Float
    let contextSummary: String
    
    /// Generate a markdown report
    func toMarkdown() -> String {
        var md = "# Rapport Post-Call\n\n"
        md += "**Durée totale :** \(formatDuration(totalDuration))\n\n"
        
        // Timeline
        md += "## Déroulé de la conversation\n\n"
        for entry in movementTimeline {
            let dur = entry.end - entry.start
            let pct = totalDuration > 0 ? Int(dur / totalDuration * 100) : 0
            md += "- \(entry.movement.emoji) **\(entry.movement.name)** — \(formatDuration(dur)) (\(pct)%)\n"
        }
        
        // Scores
        md += "\n## Scores\n\n"
        md += "- **Qualification (BANT) :** \(Int(memoryReport.qualificationScore * 100))%\n"
        md += "- **Découverte :** \(Int(memoryReport.discoveryScore * 100))%\n"
        md += "- **Fluidité :** \(Int(averageFluidityScore * 100))%\n"
        
        // Informations captées
        md += "\n## Informations captées\n\n"
        let sorted = memoryReport.slotsCollected.values.sorted(by: { $0.timestamp < $1.timestamp })
        for slot in sorted {
            md += "- **\(slot.key)** : \(slot.value) (\(slot.movement.name), \(slot.source.rawValue))\n"
        }
        
        // Missing
        if !memoryReport.missingCritical.isEmpty {
            md += "\n## ⚠️ Informations manquantes\n\n"
            for slot in memoryReport.missingCritical {
                md += "- **\(slot.label)** (\(slot.importance.rawValue))\n"
            }
        }
        
        // Context summary
        if !contextSummary.isEmpty {
            md += "\n## Résumé contextuel\n\n"
            md += contextSummary + "\n"
        }
        
        md += "\n---\n*Rapport généré automatiquement par VoiceScribe*\n"
        return md
    }
    
    private func formatDuration(_ d: TimeInterval) -> String {
        let m = Int(d) / 60
        let s = Int(d) % 60
        return "\(m)m\(String(format: "%02d", s))s"
    }
}
